algo = input('digite algo: ')
print(f'o tipo primitivo desse valor e {type(algo)}')
print(f'só tem espaços? {algo.isspace()}')
print(f'é um número? {algo.isnumeric()}')
print(f'é alfabético? {algo.isalpha()}')
print(f'é alfanúmerico? {algo.isalnum()}')
print(f'está em maiusculas? {algo.isupper()}')
print(f'está em minusculas? {algo.islower()}')
print(f'está catapilizada? {algo.istitle()}')