num = int(input('digite um número de 0 a 9999: '))
lista = str(10000 + num)
print('unidade: {}'.format(lista[4]))
print('dezena: {}'.format(lista[3]))
print('centena: {}'.format(lista[2]))
print('milhar: {}'.format(lista[1]))
